3-django/study_project/liuhao_permission/liuhao_permission/urls.py
from django.contrib import admin
from django.urls import re_path, path, include

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('web.urls')),
    path('rbac/', include(('rbac.urls', 'rbac'), namespace='rbac')),
]

3-django/study_project/liuhao_permission/rbac/service/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.urls import reverse
from django.http import QueryDict


def memory_url(request, name, *args, **kwargs):
    """
    生成带有原搜索条件的URL（替代了模板中的url）
    :param request:
    :param name:
    :return:
    """
    basic_url = reverse(name, args=args, kwargs=kwargs)

    # 当前URL中无参数
    if not request.GET:
        return basic_url

    query_dict = QueryDict(mutable=True)
    query_dict['_filter'] = request.GET.urlencode()  # mid=2&age=99

    return "%s?%s" % (basic_url, query_dict.urlencode())


def memory_reverse(request, name, *args, **kwargs):
    """
    反向生成URL
        http://127.0.0.1:8001/rbac/menu/add/?_filter=mid%3D2
        1. 在url中讲原来搜索条件，如filter后的值
        2. reverse生成原来的URL，如：/menu/list/
        3. /menu/list/?mid%3D2

    示例：
    :param request:
    :param name:
    :param args:
    :param kwargs:
    :return:
    """
    origin_url = reverse(name, args=args, kwargs=kwargs)
    origin_params = request.GET.get('_filter')
    if origin_params:
        origin_url = "%s?%s" % (origin_url, origin_params,)

    return origin_url

3-django/study_project/liuhao_permission/rbac/urls.py
from django.urls import re_path
from rbac.views import role, user, menu

urlpatterns = [
    re_path(r'^role/list/$', role.role_list, name='role_list'),
    re_path(r'^role/add/$', role.role_add, name='role_add'),
    re_path(r'^role/edit/(\d+).html$', role.role_edit, name='role_edit'),
    re_path(r'^role/del/(\d+).html$', role.role_del, name='role_del'),

    re_path(r'^user/list/$', user.user_list, name='user_list'),
    re_path(r'^user/add/$', user.user_add, name='user_add'),
    re_path(r'^user/edit/(\d+).html$', user.user_edit, name='user_edit'),
    re_path(r'^user/del/(\d+).html$', user.user_del, name='user_del'),
    re_path(r'^user/reset_pwd/(\d+).html$', user.user_reset_pwd, name='user_reset_pwd'),

    re_path(r'^menu/list/$', menu.menu_list, name='menu_list'),
    re_path(r'^menu/add/$', menu.menu_add, name='menu_add'),
    re_path(r'^menu/edit/(\d+).html$', menu.menu_edit, name='menu_edit'),
    re_path(r'^menu/del/(\d+).html$', menu.menu_del, name='menu_del'),

    re_path(r'^second/menu/add/(?P<menu_id>\d+)$', menu.second_menu_add, name='second_menu_add'),
    re_path(r'^second/menu/edit/(\d+).html$', menu.second_menu_edit, name='second_menu_edit'),
    re_path(r'^second/menu/del/(\d+).html$', menu.second_menu_del, name='second_menu_del'),

    re_path(r'^third/menu/add/(?P<second_menu_id>\d+)$', menu.third_menu_add, name='third_menu_add'),
    re_path(r'^third/menu/edit/(\d+).html$', menu.third_menu_edit, name='third_menu_edit'),
    re_path(r'^third/menu/del/(\d+).html$', menu.third_menu_del, name='third_menu_del'),

    re_path(r'^multi/permissions/$', menu.multi_permissions, name='multi_permissions'),
    re_path(r'^multi/permissions/del/(\d+)$', menu.multi_permissions_del, name='multi_permissions_del'),


    re_path(r'^distribute/permissions/$', menu.distribute_permissions, name='distribute_permissions'),
]

3-django/study_project/liuhao_permission/web/urls.py
from django.conf.urls import url
from django.urls import re_path
from web.views import customer
from web.views import payment
from web.views import account

urlpatterns = [
    # 客户管理的url
    re_path(r'^customer/list/$', customer.customer_list, name='customer_list'),
    re_path(r'^customer/add/$', customer.customer_add, name='customer_add'),
    re_path(r'^customer/edit/(?P<cid>\d+)/$', customer.customer_edit, name='customer_edit'),
    re_path(r'^customer/del/(?P<cid>\d+)/$', customer.customer_del, name='customer_del'),
    re_path(r'^customer/import/$', customer.customer_import, name='customer_import'),
    re_path(r'^customer/tpl/$', customer.customer_tpl, name='customer_tpl'),

    # 账单管理的url
    re_path(r'^payment/list/$', payment.payment_list, name='payment_list'),
    re_path(r'^payment/add/$', payment.payment_add, name='payment_add'),
    re_path(r'^payment/edit/(?P<pid>\d+)/$', payment.payment_edit, name='payment_edit'),
    re_path(r'^payment/del/(?P<pid>\d+)/$', payment.payment_del, name='payment_del'),

    # 用户登录
    re_path(r'^login/$', account.login)

]

3-django/study_project/liuhao_permission/rbac/forms/base.py
from django import forms


class BaseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)
        for name, filed in self.fields.items():
            filed.widget.attrs['class'] = 'form-control'

3-django/study_project/liuhao_permission/rbac/service/routes.py
from collections import OrderedDict
from django.conf import settings
from django.utils.module_loading import import_string  # 功能是根据字符串的形式导入模块
from django.urls import resolvers
import re


def check_url_exclude(url):
    """
    排除一些url
    :param url:
    :return:
    """
    exclude_url = settings.AUTO_DISCOVER_EXCLUDE
    for regex in exclude_url:
        if re.search(regex, url):
            return True


def recursion_urls(pre_namespace, pre_url, urlpatterns, url_ordered_dict):
    """
    用于递归循环处理所有的url
    :param pre_namespace:namespace的前缀，用于拼接name    'rbac:menu_list'
    :param pre_url: 要拼接的url的前缀，用于生成正确的url  /rbac/menu/list
    :param urlpatterns:就是路由关系   /menu/list
    :param url_ordered_dict:用于保存递归中的所有路由
    得到的路由以下面的形式进行保存
    {
        'rbac:menu_list': {name:'rbac:menu_list', url:xxx/xxx/menu/list/}
    }
    :return:
    """
    for item in urlpatterns:
        if isinstance(item, resolvers.URLPattern):  # 是非路由分发的类型，将路由添加到字典url_ordered_dict中
            if not item.name:
                continue
            name = item.name
            if pre_namespace:
                name = '%s:%s' % (pre_namespace, item.name)
                name = name.replace('admin:', '')
            url = '%s%s' % (pre_url, item.pattern)
            new_url = url.replace('/^admin', '').replace('^', '').replace('$', '')
            if check_url_exclude(url):
                continue
            url_ordered_dict[name] = {'name': name, 'url': new_url}
        elif isinstance(item, resolvers.URLResolver):
            if pre_namespace:
                if item.namespace:
                    pre_namespace = '%s:%s' % (pre_namespace, item.namespace)
                else:
                    pre_namespace = pre_namespace
            else:
                if item.namespace:
                    pre_namespace = item.namespace
                else:
                    pre_namespace = None
            pre_url = '%s%s' % (pre_url, item.pattern)
            recursion_urls(pre_namespace, pre_url, item.url_patterns, url_ordered_dict)


def get_all_url_dict():
    """
    获取到全部的url
    :return:
    """
    url_ordered_dict = OrderedDict()
    md = import_string(settings.ROOT_URLCONF)
    recursion_urls(None, '/', md.urlpatterns, url_ordered_dict)  # 递归的获取所有的路由
    return url_ordered_dict

3-django/study_project/liuhao_permission/rbac/views/menu.py
from django.shortcuts import HttpResponse, render, redirect
from rbac import models
from rbac.forms.forms import MenuForm, SecondMenuForm, ThirdMenuForm, MultiAddPermissionForm, MultiUpdatePermissionForm
from rbac.service.urls import memory_reverse
from rbac.service import routes
from rbac.service.menus_permission_dict import menus_permission_dict
from collections import OrderedDict
from django.forms import formset_factory


def menu_list(request):
    """

    :param request:
    :return:
    """
    menu_queryset = models.Menu.objects.all()
    menu_id = request.GET.get('mid')
    menu_exits = models.Menu.objects.filter(id=menu_id).first()
    if not menu_exits:
        menu_id = None
    second_menu_id = request.GET.get('sid')
    second_menu_exits = models.Permission.objects.filter(id=second_menu_id).first()
    if not second_menu_exits:
        second_menu_id = None
    if menu_id:
        second_menu = models.Permission.objects.filter(menu_id=menu_id)
    else:
        second_menu = []
    if second_menu_id:
        third_menus = models.Permission.objects.filter(pid=second_menu_id)
    else:
        third_menus = []
    return render(
        request,
        'menu_list.html',
        {'menus': menu_queryset,
         'menu_id': menu_id,
         'second_menus': second_menu,
         'second_menu_id': second_menu_id,
         'third_menus': third_menus
         }
    )


def menu_add(request):
    """
    一级菜单的增加
    :param request:
    :return:
    """
    # 跳转到这里之前的url
    origin_url = memory_reverse(request, 'rbac:menu_list')
    if request.method == 'GET':
        form = MenuForm()
        return render(request, 'menu_change.html', {'form': form, 'cancel': origin_url})
    form = MenuForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(origin_url)
    return render(request, 'menu_change.html', {'form': form, 'cancel': origin_url})


def menu_edit(request, pk):
    """
    编辑一级菜单
    :param request:
    :param pk:
    :return:
    """
    origin_url = memory_reverse(request, 'rbac:menu_list')
    obj = models.Menu.objects.filter(id=pk).first()
    if request.method == 'GET':
        form = MenuForm(instance=obj)
        return render(request, 'menu_change.html', {'form': form, 'cancel': origin_url})
    form = MenuForm(data=request.POST, instance=obj)
    if form.is_valid():
        form.save()
        return redirect(origin_url)
    return render(request, 'menu_change.html', {'form': form, 'cancel': origin_url})


def menu_del(request, pk):
    """
    删除一级菜单
    :param request:
    :param pk:
    :return:
    """
    origin_url = memory_reverse(request, 'rbac:menu_list')
    if request.method == 'GET':
        return render(request, 'delete.html', {'cancel': origin_url})
    models.Menu.objects.filter(id=pk).delete()
    return redirect(origin_url)


def second_menu_add(request, menu_id):
    """
    添加二级菜单
    :param request:
    :param menu_id:
    :return:
    """
    origin_url = memory_reverse(request, 'rbac:menu_list')
    menu_object = models.Menu.objects.filter(id=menu_id).first()
    if request.method == 'GET':
        form = SecondMenuForm(initial={'menu': menu_object})
        return render(request, 'menu_change.html', {'form': form, 'cancel': origin_url})
    form = SecondMenuForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect(origin_url)
    return render(request, 'menu_change.html', {'form': form, 'cancel': origin_url})


def second_menu_edit(request, pk):
    """
    编辑二级菜单
    :param request:
    :param pk:
    :return:
    """
    origin_url = memory_reverse(request, 'rbac:menu_list')
    second_menu_object = models.Permission.objects.filter(id=pk).first()
    if request.method == 'GET':
        form = SecondMenuForm(instance=second_menu_object)
        return render(request, 'menu_change.html', {'form': form, 'cancel': origin_url})
    form = SecondMenuForm(data=request.POST, instance=second_menu_object)
    if form.is_valid():
        form.save()
        return redirect(origin_url)
    return render(request, 'menu_change.html', {'form': form, 'cancel': origin_url})


def second_menu_del(request, pk):
    """
    删除二级菜单
    :param request:
    :param pk:
    :return:
    """
    origin_url = memory_reverse(request, 'rbac:menu_list')
    if request.method == 'GET':
        return render(request, 'delete.html', {'cancel': origin_url})
    models.Permission.objects.filter(id=pk).delete()
    return redirect(origin_url)


def third_menu_add(request, second_menu_id):
    """
    添加三级菜单（权限）
    :param request:
    :param second_menu_id:
    :return:
    """
    origin_url = memory_reverse(request, 'rbac:menu_list')
    if request.method == 'GET':
        # 可以采用选择框的方式，也可以不采用
        # second_obj = models.Permission.objects.filter(id=second_menu_id).first()
        form = ThirdMenuForm()
        return render(request, 'menu_change.html', {'form': form, 'cancel': origin_url})
    form = ThirdMenuForm(data=request.POST)
    if form.is_valid():
        second_menu_obj = models.Permission.objects.filter(id=second_menu_id).first()
        if not second_menu_obj:
            return HttpResponse('二级菜单不存在，请重新选择')
        form.instance.pid = second_menu_obj
        # instance 包含了用户提交的所有值
        # instance = models.Permission('title'='',name='', url='')
        # instance.pid = second_menu_object
        # instance.save()
        form.save()
        return redirect(origin_url)
    return render(request, 'menu_change.html', {'form': form, 'cancel': origin_url})


def third_menu_edit(request, pk):
    """
    编辑三级菜单(权限）
    :param request:
    :param pk: 当前权限的id
    :return:
    """
    origin_url = memory_reverse(request, 'rbac:menu_list')
    third_obj = models.Permission.objects.filter(id=pk).first()
    if request.method == 'GET':
        form = ThirdMenuForm(instance=third_obj)
        return render(request, 'menu_change.html', {'form': form, 'cancel': origin_url})
    form = ThirdMenuForm(data=request.POST, instance=third_obj)
    if form.is_valid():
        form.save()
        return redirect(origin_url)
    return render(request, 'menu_change.html', {'form': form, 'cancel': origin_url})


def third_menu_del(request, pk):
    origin_url = memory_reverse(request, 'rbac:menu_list')
    if request.method == 'GET':
        return render(request, 'delete.html', {'cancel': origin_url})
    models.Permission.objects.filter(id=pk).delete()
    return redirect(origin_url)


def multi_permissions(request):
    """
    批量操作权限
    :param request:
    :return:
    """
    post_type = request.GET.get('type')
    formset_add_class = formset_factory(MultiAddPermissionForm, extra=0)
    formset_update_class = formset_factory(MultiUpdatePermissionForm, extra=0)
    formset_add = None
    if request.method == 'POST' and post_type == 'add':
        formset = formset_add_class(request.POST)
        if formset.is_valid():
            post_row_list = formset.cleaned_data
            flag = True
            permission_list = []
            for i in range(formset.total_form_count()):
                row = post_row_list[i]
                if not row:
                    continue
                try:
                    permission_obj = models.Permission(**row)
                    permission_obj.validate_unique()
                    permission_list.append(permission_obj)
                except Exception as e:
                    formset.errors[0].update(e)
                    flag = False
                    formset_add = formset
            if flag:
                models.Permission.objects.bulk_create(permission_list, batch_size=20)
        else:
            formset_add = formset
    formset_update = None
    if request.method == 'POST' and post_type == 'update':
        formset = formset_update_class(data=request.POST)
        if formset.is_valid():
            post_row_list = formset.cleaned_data
            for i in range(formset.total_form_count()):
                row = post_row_list[i]
                try:
                    permission_id = row.pop('id')
                    permission_obj = models.Permission.objects.filter(id=permission_id).first()
                    for key, value in row.items():
                        setattr(permission_obj, key, value)
                    permission_obj.validate_unique()
                    permission_obj.save()
                except Exception as e:
                    formset.errors[0].update(e)
                    formset_update = formset
        else:
            formset_update = formset

    # 获取项目中所有的url
    route_dict = routes.get_all_url_dict()
    # 获取到项目中所有的url
    route_name_set = set(route_dict.keys())
    # 获取到数据库中所有的url名称
    permissions = models.Permission.objects.all().values('id', 'title', 'url', 'name', 'menu_id', 'pid_id')
    permission_name_set = set()
    permission_dict = OrderedDict()
    for item in permissions:
        permission_name_set.add(item['name'])
        permission_dict[item['name']] = item
    for name, value in permission_dict.items():
        route_row_dict = route_dict.get(name)
        if not route_row_dict:
            continue
        if value['url'] != route_row_dict['url']:
            value['url'] = '和数据库中的值不一致'

    # 计算出应该增加的name
    if not formset_add:
        add_name_list = route_name_set - permission_name_set  # 当数据库中少于自动发现的，在数据库中做增加
        formset_add = formset_add_class(
            initial=[row_dict for name, row_dict in route_dict.items() if name in add_name_list])

    # 计算出来应该删除的name
    del_name_list = permission_name_set - route_name_set  # 当数据库中的多于自动发现的，在数据库中就删除
    del_row_list = [row_dict for name, row_dict in permission_dict.items() if name in del_name_list]

    # 计算出来应该更新的name
    if not formset_update:
        update_name_list = permission_name_set & route_name_set
        formset_update = formset_update_class(
            initial=[row_dict for name, row_dict in permission_dict.items() if name in update_name_list])

3-django/study_project/liuhao_permission/rbac/templates/rbac/breadcrumb.html
<div>
    <ol class="breadcrumb no-radius no-margin" style="border-bottom: 1px solid #ddd;">
        {% for item in record_list %}
            {% if item.class %}
                <li class="{{ item.class }}">{{ item.title }}</li>
            {% else %}
                <li><a href="{{ item.url }}">{{ item.title }}</a></li>
            {% endif %}
        {% endfor %}
    </ol>
</div>

3-django/study_project/liuhao_permission/rbac/templates/rbac/delete.html
{% extends 'layout.html' %}

{% block content %}
    <div class="liuhao-container">
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p style="font-size: 13px"><i class="fa fa-warning" aria-hidden="true"></i>
                    删除后将不可恢复，是否确认删除？
                </p>
                <div style="margin-top: 20px">
                    <a href="{{ cancel }}" class="btn btn-default btn-sm">取消</a>
                    <input type="submit" value="提交" class="btn btn-danger btn-sm">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

3-django/study_project/liuhao_permission/rbac/templates/rbac/distribute_permissions.html
{% extends 'layout.html' %}
{% load rbac %}

{% block css %}
    <style>
        table {
            font-size: 12px;
        }

        .user-area ul {
            padding-left: 20px;
        }

        .user-area li {
            cursor: pointer;
            padding: 2px 0;
        }

        .user-area li a {
            display: block;
        }

        .user-area li.active {
            font-weight: bold;
            color: red;
        }

        .user-area li.active a {
            color: red;
        }

        .roles_area tr td a {
            display: block;
        }

        .roles_area tr.active {
            background-color: #f1f7fd;
            border-left: 3px solid #fdc00f;
        }

        .permission-area tr.root {
            background-color: #f1f7fd;
        }

        .permission-area tr.root td i {
            margin: 3px;
        }

        .permission-area .node {

        }

        .permission-area .node input[type="checkbox"] {
            margin: 0 5px;
        }

        .permission-area .node .parent {
            padding: 5px 0;
        }

        .permission-area .node label {
            font-weight: normal;
            margin-bottom: 0;
            font-size: 12px;
        }

        .permission-area .node .children {
            padding: 0 0 0 20px;
        }

        .permission-area .node .children .child {
            display: inline-block;
            margin: 2px 5px;
        }

        .panel-body {
            font-size: 12px;
        }

        .panel-body .form-control {
            font-size: 12px;
        }

        .select-help {
            float: left;
        }

        .select-help label {
            font-weight: normal;
            cursor: pointer;
        }

        .select-help .check-all {
            float: left;
            display: inline-block;
            margin-right: 8px;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="liuhao-container">
        <div class="col-md-3 user-area">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <i class="fa fa-book" aria-hidden="true"></i>用户信息
                </div>
                <div class="panel-body">
                    <ul>
                        {% for row in user_list %}
                            <li class="{% if row.id|safe == user_id %}active{% endif %}">
                                <a href="?uid={{ row.id }}">{{ row.name }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-3 roles_area">
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="type" value="roles">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-tags" aria-hidden="true"></i>角色信息
                        {% if user_id %}
                            <button class="right btn btn-success btn-xs" style="padding: 2px 8px; margin:-3px">
                                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                保存
                            </button>
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        提示：选中用户之后才能够给指定的用户添加角色
                    </div>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>角色</th>
                            <th>选项</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for row in role_list %}
                            <tr class="{% if row.id|safe == role_id %}active{% endif %}">
                                <td>
                                    {% if user_id %}
                                        <a href="?uid={{ user_id }}&rid={{ row.id }}">
                                            {{ row.title }}
                                        </a>
                                    {% else %}
                                        <a href="?rid={{ row.id }}">
                                            {{ row.title }}
                                        </a>
                                    {% endif %}
                                </td>
                                <td>
                                    <input type="checkbox" name="roles" value="{{ row.id }}"
                                           {% if row.id in user_roles_dict %}checked{% endif %}>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </form>
        </div>
        <div class="col-md-6 permission-area">
            <form method="post">
                {% csrf_token %}
                <input type="hidden" name="type" value="permissions">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <i class="fa fa-gavel" aria-hidden="true"></i>权限信息
                        {% if role_id %}
                            <button href="" class="right btn btn-success btn-xs" style="padding: 2px 8px; margin:-3px">
                                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                保存
                            </button>
                        {% endif %}
                    </div>
                    <div class="panel-body">
                        提示：选中角色之后才能给指定的角色添加权限
                    </div>
                    <table class="table">
                        <tbody>
                        {% for menu in menus_list %}
                            <tr class="root">
                                <td>
                                    <i class="fa fa-caret-down" aria-hidden="true"></i>
                                    {{ menu.title }}
                                    <div class="select-help">
                                        <div class="check-all">
                                            <label for="check_all_{{ menu.id }}">全选</label>
                                            <input type="checkbox" id="check_all_{{ menu.id }}" name="permissions">
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            {% if menu.children %}
                                <tr class="node">
                                    <td>
                                        {% for second_menu in menu.children %}
                                            <div class="parent">
                                                {% if second_menu.id in roles_permissions_dict %}
                                                    <input type="checkbox" id="permission_{{ second_menu.id }}"
                                                           name="permissions" value="{{ second_menu.id }}" checked>
                                                {% else %}
                                                    <input type="checkbox" id="permission_{{ second_menu.id }}"
                                                           name="permissions" value="{{ second_menu.id }}">
                                                {% endif %}
                                                <label for="permission_{{ second_menu.id }}">{{ second_menu.title }}(菜单)</label>
                                            </div>
                                            <div class="children">
                                                {% for third_menu in second_menu.children %}
                                                    <div class="child">
                                                        {% if third_menu.id in roles_permissions_dict %}
                                                            <input type="checkbox" id="permission_{{ third_menu.id }}"
                                                                   name="permissions" value="{{ third_menu.id }}"
                                                                   checked>
                                                        {% else %}
                                                            <input type="checkbox" id="permission_{{ third_menu.id }}"
                                                                   name="permissions" value="{{ third_menu.id }}">
                                                        {% endif %}
                                                        <label for="permission_{{ third_menu.id }}">{{ third_menu.title }}</label>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        {% endfor %}
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </form>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script>
        $(function () {
            $('.check-all input:checkbox').change(function () {
                $(this).parents('.root').next().find(':checkbox').prop('checked', $(this).prop('checked'))
            })
        })
    </script>
{% endblock %}

3-django/study_project/liuhao_permission/rbac/templates/rbac/role_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="liuhao-container">
        <div class="btn-group" style="margin: 5px 0">
            <a class="btn btn-default" href="{% url 'rbac:role_add' %}">
                <i class="fa fa-plus-square" aria-hidden="true"></i>添加角色
            </a>
        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>ID</th>
                <th>名称</th>
                <th>选项</th>
            </tr>
            </thead>
            <tbody>
            {% for row in roles %}
                <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.title }}</td>
                    <td>
                        <a style="color: #333333;" href="{% url 'rbac:role_edit' row.id %}"><i class="fa fa-edit"
                                                                                               aria-hidden="true"></i></a>
                        <a style="color: #d9534f;" href="{% url 'rbac:role_del' row.id %}"><i class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <nav>
            <ul class="pagination">
                {{ pager.page_html|safe }}
            </ul>
        </nav>
    </div>
{% endblock %}

3-django/study_project/liuhao_permission/rbac/templates/rbac/static_menu.html
<div class="static-menu">
    {% for item in menu_list %}
        <a href="{{ item.url }}" class="{{ active }}">
            <span class="icon-wrap"><i class="{{ item.icon }}"></i></span>{{ item.title }}</a>
    {% endfor %}
</div>

3-django/study_project/liuhao_permission/rbac/templates/rbac/user_list.html
{% extends 'layout.html' %}

{% block content %}
    <div class="liuhao-container">
        <div class="btn-group" style="margin: 5px 0">
            <a class="btn btn-default" href="{% url 'rbac:user_add' %}">
                <i class="fa fa-plus-square" aria-hidden="true"></i>添加用户
            </a>
        </div>
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th>序号</th>
                <th>ID</th>
                <th>姓名</th>
                <th>email</th>
                <th>重置密码</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in users %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ row.id }}</td>
                    <td>{{ row.name }}</td>
                    <td>{{ row.email }}</td>
                    <td>
                        <a href="{% url 'rbac:user_reset_pwd' row.id %}">
                            <i class="fa fa-wrench" aria-hidden="true"></i></a>
                    </td>
                    <td>
                        <a style="color: #333333;" href="{% url 'rbac:user_edit' row.id %}"><i class="fa fa-edit"
                                                                                               aria-hidden="true"></i></a>
                        <a style="color: #d9534f;" href="{% url 'rbac:user_del' row.id %}"><i class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <nav>
            <ul class="pagination">
                {{ pager.page_html|safe }}
            </ul>
        </nav>
    </div>
{% endblock %}